version: "3.8"
services:
    app:
        build: .
        restart: unless-stopped
        volumes:
            - "/app/node_modules"
            - ./:/app
        ports:
            - 4567:4200
        command: 
            ng serve --host 0.0.0.0